spring:

  application:
    name: Thesis
  datasource:
    url: jdbc:mysql://localhost:3306/autosalon?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    banner-mode: off
  security:
    user:
      name: admin
      password: admin
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false