spring:
  application:
    name: Thesis
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  main:
    banner-mode: off
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    clean-disabled: true
    validate-on-migrate: true

  security:
    user:
      name: ${SECURITY_USER_NAME}
      password: ${SECURITY_USER_PASSWORD}
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        period: 1d
      chain:
        cache: true
server:
  address: ${SERVER_ADDRESS}
  port: ${SERVER_PORT}
