CREATE TABLE `brands` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `country` varchar(255) NOT NULL,
  `logourl` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE `models` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `generation` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `year_from` int NOT NULL,
  `year_to` int NOT NULL,
  `brand_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK95s72g5hnsl3o0bqeuhnokdxu` (`brand_id`),
  CONSTRAINT `FK95s72g5hnsl3o0bqeuhnokdxu` FOREIGN KEY (`brand_id`) REFERENCES `brands` (`id`)
);
CREATE TABLE `salons` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` bit(1) NOT NULL,
  `apartment_number` varchar(255) NOT NULL,
  `building_number` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `code` varchar(255) NOT NULL,
  `country` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `phone` varchar(255) NOT NULL,
  `street` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE `cars` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `body_type` enum('CONVERTIBLE','COUPE','CROSSOVER','HATCHBACK','PICKUP','SEDAN','SUV','VAN','WAGON') DEFAULT NULL,
  `color` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL,
  `fuel_type` enum('DIESEL','ELECTRIC','HYBRID','LPG','PETROL') DEFAULT NULL,
  `mileage` double NOT NULL,
  `price` double NOT NULL,
  `production_year` int NOT NULL,
  `registration_number` varchar(255) NOT NULL,
  `status` enum('AVAILABLE','IN_SERVICE','RESERVED','SOLD','UNAVAILABLE') DEFAULT NULL,
  `vin` varchar(255) NOT NULL,
  `model_id` bigint DEFAULT NULL,
  `salon_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKrwe6b2vd08hb4gnst223xsna4` (`model_id`),
  KEY `FK21c5dbm1hp9peee6kdeygifg9` (`salon_id`),
  CONSTRAINT `FK21c5dbm1hp9peee6kdeygifg9` FOREIGN KEY (`salon_id`) REFERENCES `salons` (`id`),
  CONSTRAINT `FKrwe6b2vd08hb4gnst223xsna4` FOREIGN KEY (`model_id`) REFERENCES `models` (`id`)
);
CREATE TABLE `clients` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` bit(1) NOT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `first_name` varchar(255),
  `last_name` varchar(255),
  `login` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `phone` varchar(255) NOT NULL,
  `tax_number` varchar(255) NOT NULL,
  `tax_number_type` enum('NIP','OTHER','PESEL','VAT') DEFAULT NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE `employees` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` bit(1) NOT NULL,
  `email` varchar(255) NOT NULL,
  `first_name` varchar(255) NOT NULL,
  `last_name` varchar(255) NOT NULL,
  `login` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `phone` varchar(255) NOT NULL,
  `role` enum('DIRECTOR','MANAGER','SALER') DEFAULT NULL,
  `salary` double NOT NULL,
  `salon_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKlyu96cqetbgpjbv1lre1gxevu` (`salon_id`),
  CONSTRAINT `FKlyu96cqetbgpjbv1lre1gxevu` FOREIGN KEY (`salon_id`) REFERENCES `salons` (`id`)
);
CREATE TABLE `invoices` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `invoice_date` date NOT NULL,
  `invoice_name` varchar(255) NOT NULL,
  `invoice_number` varchar(255) NOT NULL,
  `invoice_tax_number` varchar(255) NOT NULL,
  `total_amount` double NOT NULL,
  `client_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK9ioqm804urbgy986pdtwqtl0x` (`client_id`),
  CONSTRAINT `FK9ioqm804urbgy986pdtwqtl0x` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`)
);
CREATE TABLE `leases` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `contract_number` varchar(255) NOT NULL,
  `end_date` date NOT NULL,
  `initial_payment` double NOT NULL,
  `monthly_payment` double NOT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `start_date` date NOT NULL,
  `status` enum('ACTIVE','COMPLETED','PENDING','TERMINATED') DEFAULT NULL,
  `total_value` double NOT NULL,
  `car_id` bigint DEFAULT NULL,
  `client_id` bigint DEFAULT NULL,
  `employee_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKaa85349rbp3xalgqpdkgpcl31` (`car_id`),
  KEY `FKdrjr7cafojk7qum81em38s391` (`client_id`),
  KEY `FK14mrx1gnxu5d8hbrrw2a6wpm3` (`employee_id`),
  CONSTRAINT `FK14mrx1gnxu5d8hbrrw2a6wpm3` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`),
  CONSTRAINT `FKdrjr7cafojk7qum81em38s391` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FKsl58twwsf720j44nmtaquqi85` FOREIGN KEY (`car_id`) REFERENCES `cars` (`id`)
);
CREATE TABLE `rents` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` bit(1) NOT NULL,
  `actual_return_date` date NOT NULL,
  `daily_rate` double NOT NULL,
  `deposit` double NOT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `rent_end` date NOT NULL,
  `rent_number` varchar(255) NOT NULL,
  `rent_start` date NOT NULL,
  `status` tinyint NOT NULL,
  `total_amount` double NOT NULL,
  `car_id` bigint DEFAULT NULL,
  `client_id` bigint DEFAULT NULL,
  `employee_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKrq6p13fdi81lci3rpsf02bydq` (`car_id`),
  KEY `FKjavoy3jpv2yvl9dqkm5vv0b5o` (`client_id`),
  KEY `FK6yadljf1kjclvdvo3dpvh99ps` (`employee_id`),
  CONSTRAINT `FK6yadljf1kjclvdvo3dpvh99ps` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`),
  CONSTRAINT `FKjavoy3jpv2yvl9dqkm5vv0b5o` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FKnt07d10bhaq3i8yjd26lnhcqf` FOREIGN KEY (`car_id`) REFERENCES `cars` (`id`)
);
CREATE TABLE `sales` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `notes` varchar(255) DEFAULT NULL,
  `payment_method` enum('CASH', 'TRANSFER') DEFAULT NULL,
  `sale_date` date NOT NULL,
  `total_amount` double NOT NULL,
  `car_id` bigint DEFAULT NULL,
  `client_id` bigint DEFAULT NULL,
  `employee_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKj6x16digtrfuse2a8gy4j5tnh` (`car_id`),
  KEY `FKbbif9cb3ecyusyms54yvwlhd5` (`client_id`),
  KEY `FK2jitm3kpqyikxeo6s0a37v99j` (`employee_id`),
  CONSTRAINT `FK2jitm3kpqyikxeo6s0a37v99j` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`),
  CONSTRAINT `FKbbif9cb3ecyusyms54yvwlhd5` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FKhb80sy23hk4kk9s4g271uw9ci` FOREIGN KEY (`car_id`) REFERENCES `cars` (`id`)
);
CREATE TABLE `payments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` bit(1) NOT NULL,
  `amount` double NOT NULL,
  `deu_date` date NOT NULL,
  `method` enum('CASH','TRANSFER') DEFAULT NULL,
  `payment_date` date NOT NULL,
  `status` enum('CANCELLED','COMPLETED','FAILED','PENDING') DEFAULT NULL,
  `invoice_id` bigint DEFAULT NULL,
  `lease_id` bigint DEFAULT NULL,
  `rent_id` bigint DEFAULT NULL,
  `sale_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKtjbeijg3xs602k6b8v42dppt4` (`sale_id`),
  KEY `FKrbqec6be74wab8iifh8g3i50i` (`invoice_id`),
  KEY `FKl5j0lkn1y3yu1s31bq3g081a3` (`lease_id`),
  KEY `FKoydp6q92idq5ojoouhtbaim23` (`rent_id`),
  CONSTRAINT `FKl5ax948m03dbdcy3i0aql4jil` FOREIGN KEY (`sale_id`) REFERENCES `sales` (`id`),
  CONSTRAINT `FKl5j0lkn1y3yu1s31bq3g081a3` FOREIGN KEY (`lease_id`) REFERENCES `leases` (`id`),
  CONSTRAINT `FKoydp6q92idq5ojoouhtbaim23` FOREIGN KEY (`rent_id`) REFERENCES `rents` (`id`),
  CONSTRAINT `FKrbqec6be74wab8iifh8g3i50i` FOREIGN KEY (`invoice_id`) REFERENCES `invoices` (`id`)
);