INSERT INTO brands (name, country, logoURL)
VALUES
('BMW', 'Germany', 'https://example.com/bmw-logo.png'),
('Mercedes-Benz', 'Germany', 'https://example.com/mercedes-logo.png'),
('Audi', 'Germany', 'https://example.com/audi-logo.png'),
('Volkswagen', 'Germany', 'https://example.com/vw-logo.png'),
('Toyota', 'Japan', 'https://example.com/toyota-logo.png'),
('Honda', 'Japan', 'https://example.com/honda-logo.png'),
('Nissan', 'Japan', 'https://example.com/nissan-logo.png'),
('Mazda', 'Japan', 'https://example.com/mazda-logo.png'),
('Lexus', 'Japan', 'https://example.com/lexus-logo.png'),
('Subaru', 'Japan', 'https://example.com/subaru-logo.png'),
('Hyundai', 'South Korea', 'https://example.com/hyundai-logo.png'),
('Kia', 'South Korea', 'https://example.com/kia-logo.png'),
('Ford', 'USA', 'https://example.com/ford-logo.png'),
('Chevrolet', 'USA', 'https://example.com/chevrolet-logo.png'),
('Tesla', 'USA', 'https://example.com/tesla-logo.png'),
('Jeep', 'USA', 'https://example.com/jeep-logo.png'),
('Volvo', 'Sweden', 'https://example.com/volvo-logo.png'),
('Peugeot', 'France', 'https://example.com/peugeot-logo.png'),
('Renault', 'France', 'https://example.com/renault-logo.png'),
('Ferrari', 'Italy', 'https://example.com/ferrari-logo.png'),
('Lamborghini', 'Italy', 'https://example.com/lamborghini-logo.png'),
('Fiat', 'Italy', 'https://example.com/fiat-logo.png'),
('Porsche', 'Germany', 'https://example.com/porsche-logo.png'),
('Jaguar', 'United Kingdom', 'https://example.com/jaguar-logo.png'),
('Land Rover', 'United Kingdom', 'https://example.com/landrover-logo.png'),
('Bentley', 'United Kingdom', 'https://example.com/bentley-logo.png'),
('Rolls-Royce', 'United Kingdom', 'https://example.com/rollsroyce-logo.png'),
('Skoda', 'Czech Republic', 'https://example.com/skoda-logo.png'),
('Seat', 'Spain', 'https://example.com/seat-logo.png'),
('Opel', 'Germany', 'https://example.com/opel-logo.png');
